version: '3'

services:
  teste-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "secret"
    ports:
      - "5432:5432"
    volumes:
      - posgres-compose:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
volumes:
  posgres-compose:

networks:
  postgres-compose-network:
    driver: bridge
